### ISSUE TITLE
Where did the checksum come from? I cannot find it on the atom github site.

### ISSUE THREAD

**Issue by 030** [andrewrothstein/ansible-atom#6]

**Comment by andrewrothstein** [comment]
I usually run the downloads manual once to compute the checksums myself in those cases where I can't find checksums on the software provider's website.  I realize that's less ideal. In such cases I feel that it's better to have me-provided checksums than none at all. If you can find checksums feel free to leave links in the comments here and/or raise a PR. I'm happy to accept with appropriate documentation.
